### PR TITLE
Properly set `limit` in Kaminari

### LINKED ISSUE #394: `current_page` Method Missing After Upgrading meilisearch-rails
**Description**  
After upgrading to the latest version (0.41.2) of `meilisearch-rails`, the `current_page` method is no longer available on the search result object when using Kaminari pagination. I downgraded to 0.41.1 and it works again. Related #376 

**Expected behavior**  
Calling `.current_page` on the search results should return the current page number.

**Current behavior**  
Calling `.current_page` results in a `NoMethodError`:

**Screenshots or Logs**

```ruby
talks = Talk.search(query_term, hits_per_page: 10, page: page)
talks.count 
# => 1
talks.current_page
# => NoMethodError: undefined method `current_page' for [#<Talk id: 1111>]:MeiliSearch::Rails::Pagination::Kaminari (NoMethodError)
```

**Environment (please complete the following information):**
- OS: macOS
- Meilisearch server version: 1.4.0
- meilisearch-rails version: 0.41.2
- Rails version: 6.1.7.10

### PR DESCRIPTION
**Pull request by ellnix**
Fixes regression in #376
Fixes #394

### CODE REVIEW

File: lib/meilisearch/rails/pagination/kaminari.rb [hunk 1]
```diff
@@ -18,11 +18,14 @@ def initialize(array, options)
         end
 
         def self.create(results, total_hits, options = {})
-          offset = ((options[:page] - 1) * options[:per_page])
-          total_hits = 0 if total_hits.nil?
-          offset = 0 if offset.nil?
-          limit = 0 if options[:per_page].nil?
-          array = new results, limit: limit, offset: offset, total_count: total_hits
+          unless MeiliSearch::Rails.active?
```
[the remark this answers is not in the document]
Comment (ellnix) [reply lib/meilisearch/rails/pagination/kaminari.rb:21]: I would if I knew which one would be merged first... Besides, there could be a patch level release with this PR while the rename is done in 0.15, that way 0.14 can have a stabler final version.

**Comment by wesharper** [comment]
Out of pure curiosity, why is the limit being set by default to `1`. Is there a configuration value that can fetch some environment-level default set by either `Meilisearch` or `Kaminari`?

**Comment by ellnix** [comment]
@wesharper The specific value of the limit doesn't matter, it's really an extension of the NullObject pattern that this gem uses when you disable Meilisearch, I used `1` as a simple value that would not cause an error. 

The problem this solves is the NullObject returns itself however you interact with it, and those instances end up in Kaminari causing all kinds of trouble. See #375

**Comment by wesharper** [comment]
Thanks for the context, @ellnix.

**Review by brunoocasali — APPROVED** [review]

**Comment by ellnix** [comment]
bors merge
